### ISSUE TITLE
Tất cả các báo cáo

### ISSUE THREAD

**Issue by AnhNT1992aitc** [AnhNT1992aitc/C-c-T-i-Ch-nh#1]
- Xuất e, w để font chữ Timenewroman
+ Tiêu đề thông tri size: 14
+ Nhãn lề trái trên cùng thông tri size:13
+ Tất cả các nội dung còn lại size:12
 - Định khổ A4:
 + Top 2
 + Bottom 2
 + Trái 0,2 (để như hiện tại)
 + Phải 0,2 (để như hiện tại)
 - Phần người lập, trưởng phòng, thủ trưởng: Căn giữa tên người lập, trưởng phòng, thủ trưởng so với phần đại diện chức danh ở trên

**Comment by Haaitc** [comment]
cần thêm thời gian để sửa lỗi này

**Comment by AnhNT1992aitc** [comment]
hiện tại lỗi này là lỗi quan trọng nên bố trí fix ngay lập tức, tránh ảnh hưởng tới module khác

**Comment by Haaitc** [comment]
đã fix ngày 08/12/2016. Test kiểm tra lại. Nếu ok thì đóng lỗi
