### ISSUE TITLE
Báo cáo theo dõi chi tiêu cấp phát/ Cột 17, 18, 19

### ISSUE THREAD

**Issue by AnhNT1992aitc** [AnhNT1992aitc/C-c-T-i-Ch-nh#2]
- Các cột có công thức phải loại trừ trường hợp công thức trong cột sinh ra số liệu nhỏ hơn 0 thì hiển thị luôn = 0. Các cột trong công thức lớn hơn 0 mới thực hiện theo công thức
VD: cột 5 =10; cột 6 = 8; cột 7=3; cột 8 = 6-5+7
 => Trên hệ thống hiện tại hàng cha vẫn hiển thị giá trị âm màu đỏ

**Comment by Haaitc** [comment]
lỗi này cần phải assigned cho người khác

**Comment by Haaitc** [comment]
assigned cho [Phuonghvit[](

**Comment by phuonghvit** [comment]
Phuonghvit. chấp nhận yêu cầu và sẽ sửa trong ngày mai.ok???
